# PgDog Configuration File
# Read Load Balancing for PostgreSQL

[general]
host = "0.0.0.0"
port = 6432
workers = 4

connect_timeout = 5000
idle_timeout = 30000
server_lifetime = 600000
healthcheck_timeout = 2000
healthcheck_interval = 1000
idle_healthcheck_interval = 1000
ban_timeout = 10000

log_connections = true
log_disconnections = true
lsn_check_delay = 0
lsn_check_interval = 1000
ban_replica_lag = 2000
openmetrics_port = 9930
shutdown_timeout = 600000

pooler_mode = "transaction"
load_balancing_strategy = "weighted_round_robin"
query_parser = "on"
read_write_strategy = "conservative"

#------------------------------------------------------------------------------
# DATABASES AND SERVERS
#------------------------------------------------------------------------------
[[databases]]
name = "appdb"
database_name = "appdb"
host = "pg-primary"
port = 5432
role = "primary"
shard = 0
lb_weight = 0

[[databases]]
name = "appdb"
database_name = "appdb"
host = "pg-replica1"
port = 5432
role = "replica"
shard = 0
lb_weight = 1

[[databases]]
name = "appdb"
database_name = "appdb"
host = "pg-replica2"
port = 5432
role = "replica"
shard = 0
lb_weight = 1
